vscode:
  extensions:
    - ms-python.python
    - bungcip.better-toml

tasks:
  - name: Development
    before: |
      pyenv install 3.11
      pyenv global 3.11
      poetry env use 3.11
      poetry install
      poetry run pre-commit install
    command: npx -y nodemon ats-project-simple/main.py
