vscode:
  extensions:
    - ms-python.python
    - bungcip.better-toml

    - hbenl.test-adapter-converter

    - filiptronicek.vscode-platform-specific-sample

tasks:
  - name: Development
    before: |
      pyenv install 3.11
      pyenv global 3.11
      poetry config virtualenvs.in-project true
      poetry env use 3.11
      poetry install
      poetry run pre-commit install
      source .venv/bin/activate
    command: npx -y nodemon main.py --print-test-tree
